name: "GH Release"
run-name: "${{ github.event.inputs.file_name }} GH Release"
env:
  GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
  TB_API_KEY: ${{ secrets.TB_API_KEY }}
on:
  workflow_dispatch:
    inputs:
      mask_log:
        description: ''
        required: true
        default: 'true'
        type: boolean    
      dl_url:
        required: true
      file_name:
        required: true

jobs:
  push-script:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Mask log
        if: ${{ github.event.inputs.mask_log == 'true' }}
        run: |
          echo "::add-mask::0"
          echo "::add-mask::1"
          echo "::add-mask::2"
          echo "::add-mask::3"
          echo "::add-mask::4"
          echo "::add-mask::5"
          echo "::add-mask::6"
          echo "::add-mask::7"
          echo "::add-mask::8"
          echo "::add-mask::9"
          echo "::add-mask::A"
          echo "::add-mask::B"
          echo "::add-mask::C"
          echo "::add-mask::D"
          echo "::add-mask::E"
          echo "::add-mask::F"
          echo "::add-mask::G"
          echo "::add-mask::H"
          echo "::add-mask::I"
          echo "::add-mask::J"
          echo "::add-mask::K"
          echo "::add-mask::L"
          echo "::add-mask::M"
          echo "::add-mask::N"
          echo "::add-mask::O"
          echo "::add-mask::P"
          echo "::add-mask::Q"
          echo "::add-mask::R"
          echo "::add-mask::S"
          echo "::add-mask::T"
          echo "::add-mask::U"
          echo "::add-mask::V"
          echo "::add-mask::W"
          echo "::add-mask::X"
          echo "::add-mask::Y"
          echo "::add-mask::Z"
          echo "::add-mask::a"
          echo "::add-mask::b"
          echo "::add-mask::c"
          echo "::add-mask::d"
          echo "::add-mask::e"
          echo "::add-mask::f"
          echo "::add-mask::g"
          echo "::add-mask::h"
          echo "::add-mask::i"
          echo "::add-mask::j"
          echo "::add-mask::k"
          echo "::add-mask::l"
          echo "::add-mask::m"
          echo "::add-mask::n"
          echo "::add-mask::o"
          echo "::add-mask::p"
          echo "::add-mask::q"
          echo "::add-mask::r"
          echo "::add-mask::s"
          echo "::add-mask::t"
          echo "::add-mask::u"
          echo "::add-mask::v"
          echo "::add-mask::w"
          echo "::add-mask::x"
          echo "::add-mask::y"
          echo "::add-mask::z"      
      - name: Setup git
        run: |
          export REPO_ID=$(echo "${{ github.event.inputs.mid }}" | sed 's/:/-/g')
          export ID=${{ github.event.inputs.mid }}
          git config --global core.compression 1
          git config --global http.postBuffer 524288000
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          wget https://github.com/cli/cli/releases/download/v2.76.2/gh_2.76.2_linux_amd64.tar.gz
          tar xvf gh_2.76.2_linux_amd64.tar.gz
          sudo mv gh_2.76.2_linux_amd64/bin/gh /usr/local/bin/

      - name: Vidlink DL
        run: |

          aria2c -x16 -j16 "${{ github.event.inputs.dl_url }}" -o blob
          
          split -b 2000000000 -da 2 blob "blob-"
          
          gh release delete ${{ github.event.inputs.file_name }} \
          --repo "gconsole00/releases" \
           -y || true
          
          gh release create "${{ github.event.inputs.file_name }}" \
          --repo "gconsole00/releases" \
          --title "${{ github.event.inputs.file_name }}" \
          --notes "${{ github.event.inputs.file_name }}"
          
          gh release upload "${{ github.event.inputs.file_name }}" blob-* \
          --repo "gconsole00/releases"
          
      - name: Send telegram
        if: failure()
        run: |
          curl "https://api.telegram.org/${{secrets.TG_BOTID_TOKEN}}/sendMessage?chat_id=${{secrets.TG_CHAT_ID}}&text=GH_Action_Failed_For%20${{ github.event.inputs.mid }}%20https://github.com/gconsole00/gllfs/actions/runs/${{github.run_id}}"
