name: "Torrention GL"
run-name: "${{ github.event.inputs.mid }} Torrention GL"
env:
  DESCRIPTION: ${{ github.event.repository.description }}
  VIDLINK_ADDON_URL: ${{ secrets.VIDLINK_ADDON_URL }}
  TB_API_KEY: ${{ secrets.TB_API_KEY }}
on:
  workflow_dispatch:
    inputs:
      mask_log:
        description: ''
        required: true
        default: 'true'
        type: boolean    
      mid:
        required: true

jobs:
  push-script:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Mask log
        if: ${{ github.event.inputs.mask_log == 'true' }}
        run: |
          echo "::add-mask::a"
          echo "::add-mask::b"
          echo "::add-mask::c"
          echo "::add-mask::d"
          echo "::add-mask::e"
          echo "::add-mask::f"       
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup
        if: ${{ !github.event.repository.is_template }}
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          aria2c -x 16 "https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-07-11-14-04/ffmpeg-N-120228-g3334bdc6e7-linux64-gpl.tar.xz"
          tar -xvf ffmpeg-N-120228-g3334bdc6e7-linux64-gpl.tar.xz
          sudo mv ffmpeg-N-120228-g3334bdc6e7-linux64-gpl/bin/* /usr/local/bin
          rm -rf ffmpeg-N-120228-g3334bdc6e7-linux64-gpl.tar.xz
          sudo rm -rf ffmpeg-N-120228-g3334bdc6e7-linux64-gpl
          wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
          chmod +x yt-dlp
          sudo mv yt-dlp /usr/local/bin
          sudo chmod +x /usr/local/bin/yt-dlp
      - name: Setup git
        run: |
          git config --global core.compression 1
          git config --global http.postBuffer 524288000
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global lfs.activitytimeout 600
          
          
      - name: TBDLGL
        run: |
          export REPO_ID=$(echo "${{ github.event.inputs.mid }}" | sed 's/:/-/g')
          export ID=${{ github.event.inputs.mid }}
          export IMDB_ID=${{ github.event.inputs.mid }}
          
          # if [[ "$ID" == *":"* ]]; then
          #   curl https://torrentio.strem.fun/qualityfilter=4k%7Csizefilter=3GB%7Cdebridoptions=nodownloadlinks,nocatalog%7Ctorbox=${{ secrets.TB_API_KEY }}/stream/series/$ID.json | jq '.streams[0].url' | xargs -L 1 wget -nv -O blob
          # else
          #   curl https://torrentio.strem.fun/qualityfilter=4k%7Csizefilter=4GB%7Cdebridoptions=nodownloadlinks,nocatalog%7Ctorbox=${{ secrets.TB_API_KEY }}/stream/movie/$ID.json | jq '.streams[0].url' | xargs -L 1 wget -nv -O blob
          # fi

          python gldownload.py

          curl --request POST \
          --fail \
          -H "PRIVATE-TOKEN: ${{ secrets.GL_PAT }}" \
          -H "Content-Type: application/json" \
          --data "{\"name\": \"$REPO_ID\", \"visibility\": \"public\"}" \
          --url "https://gitlab.com/api/v4/projects/"
          
          
          git clone https://oauth2:${{ secrets.GL_PAT }}@gitlab.com/gconsole001/$REPO_ID
          cd "$REPO_ID"
          rm -rf *
          git add . || true
          git commit -mm || true
          git push || true
          mv ../blob .
          
          git lfs track "blob"
          git add .gitattributes
          git add blob
          git commit -mm
          export GIT_LFS_FORCE_PROGRESS=1
          git push --progress

      - name: Epilogue
        run: |
          export ID=${{ github.event.inputs.mid }}
          if [[ "$ID" == *":"* ]]; then
            curl ${{secrets.STREMHUB_ADDON_URL}}/stream/series/"$ID"__nextgl.json
          else
            echo "Skipping next for movie"
          fi
          
      - name: Send telegram
        if: failure()
        run: |
          curl "https://api.telegram.org/${{secrets.TG_BOTID_TOKEN}}/sendMessage?chat_id=${{secrets.TG_CHAT_ID}}&text=GL_Action_Failed_For%20${{ github.event.inputs.mid }}%20https://github.com/gconsole00/gllfs/actions/runs/${{github.run_id}}"
